### ISSUE TITLE
pipy published package is missing csv maping

### ISSUE THREAD

**Issue by irakhlin** [guanana/pikvm-lib#6]
Hello there,
I am starting to use this library for writing a custom integration for home assistant, unfortunately I ran into an issue using some of the websocket functions that require the key map csv files. It seems the csv files are not currently present in the published pipy package.

I was able to add these lines to the end of the pyproject.toml to fix this issue, is this something you would be willing to do and publish an updated release to pipy?

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pikvm_lib = ["*.csv"]

**Comment by guanana** [comment]
Thanks for raising it, it's been fixed now
